# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed8db5d39482a4533b2c4a29fd1e76b7be0a70f0b7507c0cb78c18046decd65bd12a7fa9cd600c5815511942bb9687a912a169751b390b2e629d905c42b66beb

test:
  secret_key_base: ccf987513a111feba1c6b5260fea215af9dcd3b32a61f2681c84596f7049db5745d1980d9e4ffc9656157b27d88eb36bdfac119b8d8a0e24809997992d533869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
